const itemArray = [
  {
    imgSrc: "example.path1",
    name: "Item 1",
    brand: "Nike",
    price: 25.00,
    inCart: false,
  },
  {
    imgSrc: "example.path2",
    name: "Item 2",
    brand: "Adidas",
    price: 30.00,
    inCart: false,
  },
  {
    imgSrc: "example.path3",
    name: "Item 3",
    brand: "Puma",
    price: 20.00,
    inCart: false,
  },
  {
    imgSrc: "example.path4",
    name: "Item 4",
    brand: "Reebok",
    price: 35.00,
    inCart: false,
  },
  {
    imgSrc: "example.path5",
    name: "Item 5",
    brand: "Under Armour",
    price: 28.00,
    inCart: false,
  },
  {
    imgSrc: "example.path6",
    name: "Item 6",
    brand: "New Balance",
    price: 22.00,
    inCart: false,
  },
  {
    imgSrc: "example.path7",
    name: "Item 7",
    brand: "Asics",
    price: 26.00,
    inCart: false,
  },
  {
    imgSrc: "example.path8",
    name: "Item 8",
    brand: "Fila",
    price: 24.00,
    inCart: false,
  },
  {
    imgSrc: "example.path9",
    name: "Item 9",
    brand: "Converse",
    price: 27.00,
    inCart: false,
  },
  {
    imgSrc: "example.path10",
    name: "Item 10",
    brand: "Vans",
    price: 29.00,
    inCart: false,
  },
  {
    imgSrc: "example.path11",
    name: "Item 11",
    brand: "Skechers",
    price: 23.00,
    inCart: false,
  },
  {
    imgSrc: "example.path12",
    name: "Item 12",
    brand: "Brooks",
    price: 31.00,
    inCart: false,
  },
  {
    imgSrc: "example.path13",
    name: "Item 13",
    brand: "Nike",
    price: 32.00,
    inCart: false,
  },
  {
    imgSrc: "example.path14",
    name: "Item 14",
    brand: "Adidas",
    price: 33.00,
    inCart: false,
  },
  {
    imgSrc: "example.path15",
    name: "Item 15",
    brand: "Puma",
    price: 19.00,
    inCart: false,
  },
  {
    imgSrc: "example.path16",
    name: "Item 16",
    brand: "Reebok",
    price: 21.00,
    inCart: false,
  },
  {
    imgSrc: "example.path17",
    name: "Item 17",
    brand: "Under Armour",
    price: 34.00,
    inCart: false,
  },
  {
    imgSrc: "example.path18",
    name: "Item 18",
    brand: "New Balance",
    price: 36.00,
    inCart: false,
  },
  {
    imgSrc: "example.path19",
    name: "Item 19",
    brand: "Asics",
    price: 37.00,
    inCart: false,
  },
  {
    imgSrc: "example.path20",
    name: "Item 20",
    brand: "Fila",
    price: 38.00,
    inCart: false,
  },
  {
    imgSrc: "example.path21",
    name: "Item 21",
    brand: "Converse",
    price: 39.00,
    inCart: false,
  },
  {
    imgSrc: "example.path22",
    name: "Item 22",
    brand: "Vans",
    price: 40.00,
    inCart: false,
  },
  {
    imgSrc: "example.path23",
    name: "Item 23",
    brand: "Skechers",
    price: 41.00,
    inCart: false,
  },
  {
    imgSrc: "example.path24",
    name: "Item 24",
    brand: "Brooks",
    price: 42.00,
    inCart: false,
  },
  {
    imgSrc: "example.path25",
    name: "Item 25",
    brand: "Nike",
    price: 43.00,
    inCart: false,
  },
  {
    imgSrc: "example.path26",
    name: "Item 26",
    brand: "Adidas",
    price: 44.00,
    inCart: false,
  },
  {
    imgSrc: "example.path27",
    name: "Item 27",
    brand: "Puma",
    price: 45.00,
    inCart: false,
  },
  {
    imgSrc: "example.path28",
    name: "Item 28",
    brand: "Reebok",
    price: 46.00,
    inCart: false,
  },
  {
    imgSrc: "example.path29",
    name: "Item 29",
    brand: "Under Armour",
    price: 47.00,
    inCart: false,
  },
  {
    imgSrc: "example.path30",
    name: "Item 30",
    brand: "New Balance",
    price: 48.00,
    inCart: false,
  },
  {
    imgSrc: "example.path31",
    name: "Item 31",
    brand: "Asics",
    price: 49.00,
    inCart: false,
  },
  {
    imgSrc: "example.path32",
    name: "Item 32",
    brand: "Fila",
    price: 50.00,
    inCart: false,
  },
  {
    imgSrc: "example.path33",
    name: "Item 33",
    brand: "Converse",
    price: 51.00,
    inCart: false,
  },
  {
    imgSrc: "example.path34",
    name: "Item 34",
    brand: "Vans",
    price: 52.00,
    inCart: false,
  },
  {
    imgSrc: "example.path35",
    name: "Item 35",
    brand: "Skechers",
    price: 53.00,
    inCart: false,
  },
  {
    imgSrc: "example.path36",
    name: "Item 36",
    brand: "Brooks",
    price: 54.00,
    inCart: false,
  },
  {
    imgSrc: "example.path37",
    name: "Item 37",
    brand: "Nike",
    price: 55.00,
    inCart: false,
  },
  {
    imgSrc: "example.path38",
    name: "Item 38",
    brand: "Adidas",
    price: 56.00,
    inCart: false,
  },
  {
    imgSrc: "example.path39",
    name: "Item 39",
    brand: "Puma",
    price: 57.00,
    inCart: false,
  },
  {
    imgSrc: "example.path40",
    name: "Item 40",
    brand: "Reebok",
    price: 58.00,
    inCart: false,
  },
  {
    imgSrc: "example.path41",
    name: "Item 41",
    brand: "Under Armour",
    price: 59.00,
    inCart: false,
  },
  {
    imgSrc: "example.path42",
    name: "Item 42",
    brand: "New Balance",
    price: 60.00,
    inCart: false,
  },
  {
    imgSrc: "example.path43",
    name: "Item 43",
    brand: "Asics",
    price: 61.00,
    inCart: false,
  },
  {
    imgSrc: "example.path44",
    name: "Item 44",
    brand: "Fila",
    price: 62.00,
    inCart: false,
  },
  {
    imgSrc: "example.path45",
    name: "Item 45",
    brand: "Converse",
    price: 63.00,
    inCart: false,
  },
  {
    imgSrc: "example.path46",
    name: "Item 46",
    brand: "Vans",
    price: 64.00,
    inCart: false,
  },
  {
    imgSrc: "example.path47",
    name: "Item 47",
    brand: "Skechers",
    price: 65.00,
    inCart: false,
  },
  {
    imgSrc: "example.path48",
    name: "Item 48",
    brand: "Brooks",
    price: 66.00,
    inCart: false,
  },
];

export default itemArray;
